using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            string[,] arr = new string[71, 48] {{"Empty","a" ,"b" ,"c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z","=","!","*","-","+","/","[0-9]","&","|","$"," double "," single ",",","<",">","[","]","{","}",";","~"},
                                               { "0"   ,"nill" ,"nill","27","nill", "34"  ,"nill" ,"nill" ,"nill","38"  ,"nill" ,"nill","66"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"76" ,"84" ,"nill" ,"nill" ,"92" ,"nill" ,"nill" ,"nill" ," ASS_OP 23","REL_OP 6" ,  "Ari_OP 4" , "Ari_OP 3","Ari_OP 2" , "Ari_OP 19" ,"Constant 1", "12","64" ,"9","7","14" , "comma16","REL_OP 21","relational operator 25" ,"60","nill","62","nill" ,"semiclon 101" ,"Logic op 59" },
                                               { "1"   ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill","Constant 1" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
                                               { "5"   ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill","nill"   ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"7"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill","qoution 8 "  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "9"   ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"10"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"10"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" , "Single comment 11"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "12"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ," Logic operators 13" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"14"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill","Quotation Mark 15","nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"17"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill","Acess_operator 18"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "19"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill"," multiple line comment 20  "  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "21"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"relational operator 22 "  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "23"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill", "ASSignment operators 24" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "25"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" , "relational operator  25"    ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "27"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill", "28"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "28","29"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill","32"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "29"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"30"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"30"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill"  ,"nill" ,"nill" ,"nill" ,"nill" ,"String 31" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "32"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill", "char 33","nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "34"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill","35","nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"35" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill", "36"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"36"  ,"nill" ,"nill" ,"nill" ,"nill","Condtition 37 "  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"38"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill","Condtition 39"   ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill","40","46"  ,"nill" ,"nill" ,"nill" ,"nill","49"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"40"  ,"nill" ,"nill" ,"41", "nill"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"41"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"42"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"42"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill","43"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"43"  ,"nill" ,"nill" ,"nill" ,"44"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"44" ,"nill" ,"nill" ,"nill" ,"nill" ,"Inclusion 45"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"46"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"47"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"47"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"Float 48","nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"49"  ,"nill" ,"nill" ,"nill" ,"nill" ,"50"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "50"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill", "51"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"51" ,"52"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "52"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill","53"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "53" ,"nill" ,"nill" ,"nill" ,"nill" ,"54"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"54"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill","55"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "55"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill","56" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"56"  ,"nill" ,"nill" ,"nill" ,"nill","57"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"57"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill"," loop 58" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"60"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill"  ,"Braces 61"  ,"nill" ,"nill" ,"nill" ,"nill" },
{ "62"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill", "Braces 63"   ,"nill" ,"nill" },
{"64"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ," Logic_OP 65"    ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"66"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill","67"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"67"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill","68"  ,"nill" ,"nill" ,"70"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"Integer 79" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"68"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill","Struct 69"   ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"70"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"71"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"71"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill","72"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"72"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill","73"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "73" ,"nill" ,"nill" ,"nill" ,"nill" ,"74"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"74"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"Loop 75" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"76"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"77"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill", "81"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"77"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"78"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"78"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"SInteger","nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"79" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill","Sfloat 80"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "81"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill","82"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"82"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill","Break 83"    ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"84" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill","85"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "85"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"86"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "86"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"87"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "87"  ,"nill" ,"88"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"88" ,"89"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "89"  ,"nill" ,"nill" ,"90"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"90"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill","Return 91"    ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"92"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"93"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "93"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"94"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "94"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"95"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{"95"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"96"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "96"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"97"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "97"  ,"nill" ,"nill" ,"nill" ,"nill" ,"98"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "98" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill", "99"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" },
{ "99"  ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill", "Void 100"    ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" ,"nill" }};


            //  scanner.words("low 3num=5;");
            // scanner.words("Loopwhen(counter<num){");
            // scanner.words("(kjfkejf 12 23 2323 {.2; )");
            scanner2 sc = new scanner2();
             sc.Scanner("[ lowf 3num = 10.10 ] \n $$$ wlaaaaaaaaaa \n loopwhen { if { i == 3 } && { i != 67 } } \n" +
               " /$ END $/ \n worthless ( iowf _new = 25.5 ; )");
            // sc.Scanner("kmsdksn _int");
            Console.ReadKey();
           
        }
    }
}
